jobs:
  build:
    env:
      PRIMARY_JAVA_VERSION: 11
    name: Build Smack
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache Maven
      uses: actions/cache@v2
      with:
        key: maven-${{ hashFiles('**/build.gradle') }}
        path: ~/.m2/repository
        restore-keys: 'maven-

          '
    - continue-on-error: true
      name: Cache Gradle
      uses: actions/cache@v2
      with:
        key: gradle-caches-${{ hashFiles('**/build.gradle') }}
        path: ~/.gradle/caches
        restore-keys: gradle-caches
    - continue-on-error: true
      name: Cache Android SDK
      uses: actions/cache@v2
      with:
        key: android-${{ hashFiles('build.gradle') }}
        path: '~/.android/sdk

          '
        restore-keys: 'android-

          '
    - continue-on-error: true
      name: Install GraphViz
      run: sudo apt update && sudo apt install graphviz
    - continue-on-error: true
      name: Install Android SDK Manager
      uses: android-actions/setup-android@v2
    - continue-on-error: true
      name: Install Android SDK
      run: 'sdkmanager "platforms;android-19"

        '
    - continue-on-error: true
      name: Gradle Check
      run: ./gradlew check --stacktrace
    - continue-on-error: true
      name: Gradle publish
      run: ./gradlew publishToMavenLocal --stacktrace
    - continue-on-error: true
      if: ${{ matrix.java == env.PRIMARY_JAVA_VERSION }}
      name: Javadoc
      run: ./gradlew javadocAll --stacktrace
    - continue-on-error: true
      env:
        COVERALLS_REPO_TOKEN: S2ecSJja2cKJa9yv45C8ZFPohXuRrTXKd
      if: ${{ matrix.java == env.PRIMARY_JAVA_VERSION }}
      name: Jacoco Test Coverage
      run: ./gradlew jacocoRootReport coveralls
    - continue-on-error: true
      name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: smack-java-${{ matrix.java }}
        path: 'smack-*/build/libs/*.jar

          !**/*-test-fixtures.jar

          !**/*-tests.jar

          '
    strategy:
      matrix:
        java:
        - 11
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
